.\"	$OpenBSD$
.\"
.\" Copyright (c) 2022 Aaron Bieber <abieber@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd April 7, 2022
.Dt PKG 8
.Os
.Sh NAME
.Nm pkg
.Nd a wraper for OpenBSD's pkg* tools
.Sh SYNOPSIS
.Nm
.Op Ar delete Ar package
.Op Ar info Ar package
.Op Ar install Ar package
.Op Ar pkginfo Ar package
.Op Ar search Ar string
.Sh DESCRIPTION
.Nm
is a
.Xr perl 1
script that allows easier package management and more extensive searching.
.Pp
.Nm
uses
.Xr sqlports 5 for quicker, full text searching of COMMENT and DESCR fields.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Ar delete package
Deletes
.Nm package .
This is a wrapper for
.Xr pkg_delete 1
.
It is also aliased to
.Nm del ,
and
.Nm rm .
.It Ar info package
Fetches
.Nm package
information.
This is a wrapper for
.Xr pkg_info 1
.
It is aliased to
.Nm inf .
.It Ar install package
A wrapper for
.Xr pkg_add 1 .
Aliased to
.Nm i .
.It Ar pkginfo FULLPKGNAME
Intended for use with tools like
.Xr fzf 1 .
This lets one quickly look up
.Nm COMMENT
and
.Nm DESCRIPTION
for a given
.Nm FULLPKGNAME .
Aliased to
.Nm pi .
.It Ar search string
Search a packages
.Nm COMMENT
and
.Nm DESCR
for an arbitrary string.
Returns
.Nm FULLPKGNAME .
.El
.Sh HISTORY
.Nm
was written in 2001, removed from base in 2012, revived and enhanced in 2018
and 2022.
.Sh AUTHORS
.An -nosplit
.Nm
was originally written by
.An Marc Espie Aq Mt espie@openbsd.org .
Rewrite by
.An Aaron Bieber Aq Mt abieber@openbsd.org .
